# ===================================================================
# Spring Boot configuration for the "local" profile.
#
# This configuration overrides the application.yaml file.
#
#         TO BE USED FOR LOCAL DEVELOPMENTS
#
# ===================================================================
# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
  profiles:
    active: test

  devtools:
    restart:
      enabled: true
  jackson:
    serialization.indent_output: true

logging:
  level:
    eu.stelliant: DEBUG
    org.springframework: INFO
    #org.springframework.integration: DEBUG
    #org.springframework.web.client: DEBUG

sinapps:
  api:
    truststore: classpath:security/keystore.pks
    storepass: storepass
    baseUrl: https://sinapps-ird-v2.demo.darva.com
    loginPath: /core/api/login
    login: 28953sinapps
    password: bb*1xSZO
    debugging: true

itex:
  file:
    path: /Users/guytou/TBOX/WORK/STELLIANT/itex
    name: output.log