# ===================================================================
# Spring Boot configuration for the "local" profile.
#
# This configuration overrides the application.yaml file.
#
#         TO BE USED FOR LOCAL DEVELOPMENTS
#
# ===================================================================
# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
  profiles:
    active: local
  devtools:
    restart:
      enabled: true
  jackson:
    serialization.indent_output: true

logging:
  file: sinapps.log
  path: /Users/guytou/TBOX/WORK/STELLIANT/sinapps
  level:
    eu.stelliant: ERROR
    org.springframework: ERROR
    org.springframework.integration: DEBUG
    org.springframework.web.client: ERROR

sinapps:
  api:
    host: https://sinapps-ird-v2.demo.darva.com
    ssl:
      truststore: classpath:security/keystore.pks
      storepass: storepass
    login:
      mapping: /core/api/login
      username: 28953sinapps
      password: bb*1xSZO

itex:
  file:
    path: /Users/guytou/TBOX/WORK/STELLIANT/itex
