package eu.stelliant.sinapps.module.api;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.catchThrowable;

import com.darva.sinapps.api.client.expertise.model.ListeAbstractMissions;
import com.darva.sinapps.api.client.expertise.model.RessourceMission;
import com.darva.sinapps.api.client.expertise.model.RessourcePartenaire;
import com.darva.sinapps.api.client.expertise.model.RessourceUser;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.exc.InvalidFormatException;
import com.fasterxml.jackson.databind.exc.MismatchedInputException;
import eu.stelliant.model.DataTypes;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;

public class ApiDataTypesTest extends TestApiSetup {

  @Autowired
  ObjectMapper objectMapper;

  @Test
  public void date_() {

    OffsetDateTime offsetDateTime = OffsetDateTime
        .of(LocalDateTime.parse("2015-12-05T10:57:47"), ZoneOffset.of("+0200"));
    assertThat(offsetDateTime).toString().equals("2015-12-05T10:57:47+0200");
  }

  @Test
  public void date_colon() {

    OffsetDateTime offsetDateTime = OffsetDateTime
        .of(LocalDateTime.parse("2015-12-05T10:57:47"), ZoneOffset.of("+02:00"));
    assertThat(offsetDateTime).toString().equals("2015-12-05T10:57:47+02:00");
  }


  @Test
  public void date_should_throw_jackson_InvalidFormatException() {

    // Given
    String jsonDataTypes = "{"
        + "\"dateType\": \"2018-05-17T10:57:47+02:00\""
        + "}";

    // When
    Throwable exception = catchThrowable(() -> objectMapper
        .readValue(jsonDataTypes, DataTypes.class));

    // Then
    assertThat(exception).isInstanceOf(InvalidFormatException.class)
        .hasMessageContaining("Cannot deserialize value of type `java.time.OffsetDateTime`");
  }

  @Test
  public void date_should_be_parsed() throws IOException {

    // Given
    String jsonDataTypes = "{"
        + "\"dateType\": \"2018-05-17T10:57:47+0200\""
        + "}";

    // When
    DataTypes dataTypes = objectMapper.readValue(jsonDataTypes, DataTypes.class);

    // Then
    assertThat(dataTypes.getDateType().getOffset().toString()).isEqualTo("+02:00");
  }

  @Test
  public void array_should_throw_jackson_MismatchedInputException() {

    // Given
    String jsonDataTypes = "{\"arrayType\": {"
        + " \"/assureurId\": {"
        + "   \"type\": {"
        + "     \"array\": {"
        + "       \"type\": \"BSONObjectID\""
        + "     }"
        + "   },"
        + "   \"optional\": true"
        + " },"
        + " \"/prestataireId\": {"
        + "   \"type\": {"
        + "     \"array\": {"
        + "       \"type\": \"BSONObjectID\""
        + "     }"
        + "   },"
        + "   \"optional\": true"
        + " }"
        + "}";

    // When
    Throwable exception = catchThrowable(() -> objectMapper
        .readValue(jsonDataTypes, DataTypes.class));

    // Then
    assertThat(exception).isInstanceOf(MismatchedInputException.class)
        .hasMessageContaining("Cannot deserialize instance of `java.util.ArrayList`");
  }

  @Test
  public void array_should_be_parsed() throws IOException {

    // Given
    String jsonDataTypes = "{\"arrayType\": ["
        + " {"
        + "   \"/assureurId\": {"
        + "     \"type\": {"
        + "       \"array\": {"
        + "         \"type\": \"BSONObjectID\""
        + "       }"
        + "     },"
        + "     \"optional\": true"
        + "   }"
        + " }, {"
        + "   \"/prestataireId\": {"
        + "     \"type\": {"
        + "       \"array\": {"
        + "         \"type\": \"BSONObjectID\""
        + "       }"
        + "     },"
        + "     \"optional\": true"
        + "   }"
        + " }]"
        + "}";

    // When
    DataTypes dataTypes = objectMapper.readValue(jsonDataTypes, DataTypes.class);

    // Then
    assertThat(dataTypes.getArrayType().size()).isEqualTo(2);
  }

  @Test
  public void user_should_be_parsed() throws IOException {

    // Given
    String jsonDataTypes = "{\n"
        + "    \"href\": \"/core/api/partenaire/users/5b489dc6150000fd00992055\",\n"
        + "    \"properties\": {\n"
        + "        \"partenaireId\": \"5b489dc6130000be0078176b\",\n"
        + "        \"personne\": {\n"
        + "            \"nom\": \"SINAPPS TEXA\",\n"
        + "            \"prenom\": \"\",\n"
        + "            \"adresse\": {},\n"
        + "            \"coordonnees\": {\n"
        + "                \"telPersonnel\": \"               \",\n"
        + "                \"email\": \"accompagnement_client@darva.com\"\n"
        + "            }\n"
        + "        },\n"
        + "        \"login\": \"28953sinapps\",\n"
        + "        \"roles\": [\n"
        + "            {\n"
        + "                \"name\": \"Qualifieur\",\n"
        + "                \"label\": \"Prestataire Qualifieur\"\n"
        + "            },\n"
        + "            {\n"
        + "                \"name\": \"Chiffreur\",\n"
        + "                \"label\": \"Prestataire Chiffreur\"\n"
        + "            },\n"
        + "            {\n"
        + "                \"name\": \"Planificateur\",\n"
        + "                \"label\": \"Prestataire Planificateur\"\n"
        + "            },\n"
        + "            {\n"
        + "                \"name\": \"Comptable\",\n"
        + "                \"label\": \"Prestataire Comptable\"\n"
        + "            }\n"
        + "        ],\n"
        + "        \"id\": \"5b489dc6150000fd00992055\",\n"
        + "        \"version\": 1,\n"
        + "        \"dateDeCreation\": \"2018-07-13T14:40:38+0200\",\n"
        + "        \"dateDeDerniereModification\": \"2018-07-13T14:40:38+0200\"\n"
        + "    },\n"
        + "    \"links\": [\n"
        + "        {\n"
        + "            \"rel\": \"commands\",\n"
        + "            \"href\": \"/core/api/partenaire/users/5b489dc6150000fd00992055/commands?referer=commands\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"rel\": \"events\",\n"
        + "            \"href\": \"/core/api/partenaire/users/5b489dc6150000fd00992055/events?referer=events\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"rel\": \"linked-events\",\n"
        + "            \"href\": \"/core/api/partenaire/users/5b489dc6150000fd00992055/linkedEvents?referer=linked-events\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"rel\": \"eventsNotCreatedByMe\",\n"
        + "            \"href\": \"/core/api/partenaire/users/5b489dc6150000fd00992055/othersEvents?referer=eventsNotCreatedByMe\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"rel\": \"partenaire\",\n"
        + "            \"href\": \"/core/api/partenaire/partenaires/5b489dc6130000be0078176b?referer=partenaire\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"rel\": \"abstractMissions\",\n"
        + "            \"href\": \"/core/api/common/missions?prestataireId=5b489dc6130000be0078176b&etatMission=MissionRecue&etatMission=RendezVousChiffragePris&etatMission=ChiffrageEnAttenteDeValidation&etatMission=ChiffrageValide&etatMission=TravauxPlanifies&etatMission=FactureTravauxDeposee&etatMission=FactureGestionDeposee&referer=abstractMissions\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"rel\": \"missions\",\n"
        + "            \"href\": \"/core/api/covea/missions?prestataireId=5b489dc6130000be0078176b&etatMission=MissionRecue&etatMission=RendezVousChiffragePris&etatMission=ChiffrageEnAttenteDeValidation&etatMission=ChiffrageValide&etatMission=TravauxPlanifies&etatMission=FactureTravauxDeposee&etatMission=FactureGestionDeposee&referer=missions\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"rel\": \"marcheRenMissions\",\n"
        + "            \"href\": \"/core/api/marche-ren/missions?prestataireId=5b489dc6130000be0078176b&etatMission=MissionRecue&etatMission=RendezVousChiffragePris&etatMission=ChiffrageEnAttenteDeValidation&etatMission=ChiffrageValide&etatMission=TravauxPlanifies&etatMission=FactureTravauxDeposee&etatMission=FactureGestionDeposee&referer=marcheRenMissions\"\n"
        + "        }\n"
        + "    ]\n"
        + "}";

    // When
    RessourceUser mapped = objectMapper
        .readValue(jsonDataTypes,
                   RessourceUser.class);

    // Then
    assertThat(mapped.getProperties()).isNotNull();
  }

  @Test
  public void partenaire_should_be_parsed() throws IOException {

    // Given
    String jsonDataTypes = "{\n"
        + "    \"href\": \"/core/api/partenaire/partenaires/5b489dc6130000be0078176b\",\n"
        + "    \"properties\": {\n"
        + "        \"numeroClient\": \"28953\",\n"
        + "        \"nom\": \"TEXA Point d'entree unique\",\n"
        + "        \"typePartenaire\": {\n"
        + "            \"name\": \"Expert\",\n"
        + "            \"label\": \"Expert\"\n"
        + "        },\n"
        + "        \"adresse\": {\n"
        + "            \"adresse1\": \"adresse 1\",\n"
        + "            \"adresse2\": \"adresse 2\",\n"
        + "            \"codePostal\": \"18000\",\n"
        + "            \"localite\": \"BOURGES\",\n"
        + "            \"codePays\": \"FR\"\n"
        + "        },\n"
        + "        \"agrement\": [\n"
        + "            {\n"
        + "                \"name\": \"Covea\",\n"
        + "                \"label\": \"Covea\"\n"
        + "            }\n"
        + "        ],\n"
        + "        \"telephone\": \"0549494949\",\n"
        + "        \"agreePar\": [\n"
        + "            {\n"
        + "                \"assureurId\": \"5b489d59130000610078169e\"\n"
        + "            },\n"
        + "            {\n"
        + "                \"assureurId\": \"5b489d591300006100781696\"\n"
        + "            },\n"
        + "            {\n"
        + "                \"assureurId\": \"5b489d591300006100781693\"\n"
        + "            },\n"
        + "            {\n"
        + "                \"assureurId\": \"5b489d5913000063007816a3\"\n"
        + "            },\n"
        + "            {\n"
        + "                \"assureurId\": \"5b489d591300006200781699\"\n"
        + "            },\n"
        + "            {\n"
        + "                \"assureurId\": \"5b489d5913000061007816a1\"\n"
        + "            },\n"
        + "            {\n"
        + "                \"assureurId\": \"5b489d59130000620078169b\"\n"
        + "            }\n"
        + "        ],\n"
        + "        \"id\": \"5b489dc6130000be0078176b\",\n"
        + "        \"version\": 0,\n"
        + "        \"dateDeCreation\": \"2018-07-13T14:40:38+0200\",\n"
        + "        \"dateDeDerniereModification\": \"2018-07-13T14:40:38+0200\"\n"
        + "    },\n"
        + "    \"links\": [\n"
        + "        {\n"
        + "            \"rel\": \"commands\",\n"
        + "            \"href\": \"/core/api/partenaire/partenaires/5b489dc6130000be0078176b/commands?referer=commands\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"rel\": \"events\",\n"
        + "            \"href\": \"/core/api/partenaire/partenaires/5b489dc6130000be0078176b/events?referer=events\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"rel\": \"linked-events\",\n"
        + "            \"href\": \"/core/api/partenaire/partenaires/5b489dc6130000be0078176b/linkedEvents?referer=linked-events\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"rel\": \"eventsNotCreatedByMe\",\n"
        + "            \"href\": \"/core/api/partenaire/partenaires/5b489dc6130000be0078176b/othersEvents?referer=eventsNotCreatedByMe\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"rel\": \"expertMissions\",\n"
        + "            \"href\": \"/core/api/covea-expert/missions?prestataireId=5b489dc6130000be0078176b&referer=expertMissions\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"rel\": \"abstractMissions\",\n"
        + "            \"href\": \"/core/api/common/missions?prestataireId=5b489dc6130000be0078176b&referer=abstractMissions\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"rel\": \"users\",\n"
        + "            \"href\": \"/core/api/partenaire/users?partenaireId=5b489dc6130000be0078176b&referer=users\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"rel\": \"profilPublic\",\n"
        + "            \"href\": \"/core/api/partenaire/partenaires/5b489dc6130000be0078176b/public?referer=profilPublic\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"rel\": \"partenairesAvecAgrement\",\n"
        + "            \"href\": \"/core/api/partenaire/partenaires/5b489dc6130000be0078176b/partenairesAvecAgrement?referer=partenairesAvecAgrement\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"rel\": \"current\",\n"
        + "            \"href\": \"/core/api/partenaire/partenaires/5b489dc6130000be0078176b?referer=current\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"rel\": \"last\",\n"
        + "            \"href\": \"/core/api/covea/partenaires/5b489dc6130000be0078176b/versions/0?referer=last\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"rel\": \"first\",\n"
        + "            \"href\": \"/core/api/covea/partenaires/5b489dc6130000be0078176b/versions/0?referer=first\"\n"
        + "        }\n"
        + "    ]\n"
        + "}";

    // When
    RessourcePartenaire mapped = objectMapper
        .readValue(jsonDataTypes,
                   RessourcePartenaire.class);

    // Then
    assertThat(mapped.getProperties()).isNotNull();
  }

  @Test
  public void missions_should_be_parsed() throws IOException {

    // Given
    String jsonDataTypes = "{\n"
        + "    \"href\": \"/core/api/common/missions?prestataireId=5b489dc6130000be0078176b&nbPage=1&nbElements=16\",\n"
        + "    \"properties\": {\n"
        + "        \"totalNumberOfElements\": 2,\n"
        + "        \"noPage\": 1,\n"
        + "        \"nbElementPerPage\": 16,\n"
        + "        \"nbElements\": 2,\n"
        + "        \"firstPage\": \"/core/api/common/missions?prestataireId=5b489dc6130000be0078176b&nbPage=1&nbElements=16\",\n"
        + "        \"lastPage\": \"/core/api/common/missions?prestataireId=5b489dc6130000be0078176b&nbPage=1&nbElements=16\"\n"
        + "    },\n"
        + "    \"items\": [\n"
        + "        {\n"
        + "            \"href\": \"/core/api/covea-expert/missions/5b489f0910000044017610bd\",\n"
        + "            \"properties\": {\n"
        + "                \"id\": \"5b489f0910000044017610bd\",\n"
        + "                \"assureurId\": \"5b489d591300006100781693\",\n"
        + "                \"lieu\": \"Lille, 59777\",\n"
        + "                \"departement\": \"59\",\n"
        + "                \"difficulteBloquante\": false,\n"
        + "                \"typeMission\": {\n"
        + "                    \"name\": \"ExpertiseCovea\",\n"
        + "                    \"label\": \"Expertise\"\n"
        + "                },\n"
        + "                \"pourcentageAvancement\": 0,\n"
        + "                \"prestataireId\": \"5b489dc6130000be0078176b\",\n"
        + "                \"numero\": \"0004\",\n"
        + "                \"dateDeMissionnement\": \"2018-07-03T10:00:00+0200\",\n"
        + "                \"difficulteNonBloquante\": false,\n"
        + "                \"etapeMission\": {\n"
        + "                    \"name\": \"PrestataireMissionne\",\n"
        + "                    \"label\": \"Prestataire missionné\"\n"
        + "                },\n"
        + "                \"cloture\": false,\n"
        + "                \"nature\": {\n"
        + "                    \"name\": \"Incendie\",\n"
        + "                    \"label\": \"Incendie\"\n"
        + "                },\n"
        + "                \"finDeMissionDemandee\": false,\n"
        + "                \"referenceSinistre\": \"REF-EAD-20180713-02\",\n"
        + "                \"cause\": {\n"
        + "                    \"name\": \"AppareilChauffage\",\n"
        + "                    \"label\": \"Appareil de chauffage\"\n"
        + "                },\n"
        + "                \"assure\": \"Zénith Arena Lille\",\n"
        + "                \"etatPrestation\": {\n"
        + "                    \"name\": \"PrestationRecue\",\n"
        + "                    \"label\": \"Prestation reçue\"\n"
        + "                },\n"
        + "                \"mandant\": \"covea-expert\",\n"
        + "                \"dateCreation\": \"2018-07-13T14:46:01+0200\"\n"
        + "            },\n"
        + "            \"links\": []\n"
        + "        },\n"
        + "        {\n"
        + "            \"href\": \"/core/api/covea-expert/missions/5b489ec610000035017610b4\",\n"
        + "            \"properties\": {\n"
        + "                \"id\": \"5b489ec610000035017610b4\",\n"
        + "                \"assureurId\": \"5b489d591300006100781693\",\n"
        + "                \"lieu\": \"Lille, 59777\",\n"
        + "                \"departement\": \"59\",\n"
        + "                \"difficulteBloquante\": false,\n"
        + "                \"typeMission\": {\n"
        + "                    \"name\": \"ExpertiseCovea\",\n"
        + "                    \"label\": \"Expertise\"\n"
        + "                },\n"
        + "                \"pourcentageAvancement\": 0,\n"
        + "                \"prestataireId\": \"5b489dc6130000be0078176b\",\n"
        + "                \"numero\": \"0004\",\n"
        + "                \"dateDeMissionnement\": \"2018-07-03T10:00:00+0200\",\n"
        + "                \"difficulteNonBloquante\": false,\n"
        + "                \"etapeMission\": {\n"
        + "                    \"name\": \"PrestataireMissionne\",\n"
        + "                    \"label\": \"Prestataire missionné\"\n"
        + "                },\n"
        + "                \"cloture\": false,\n"
        + "                \"nature\": {\n"
        + "                    \"name\": \"Incendie\",\n"
        + "                    \"label\": \"Incendie\"\n"
        + "                },\n"
        + "                \"finDeMissionDemandee\": false,\n"
        + "                \"referenceSinistre\": \"REF-ESS-20180713-01\",\n"
        + "                \"cause\": {\n"
        + "                    \"name\": \"AppareilChauffage\",\n"
        + "                    \"label\": \"Appareil de chauffage\"\n"
        + "                },\n"
        + "                \"assure\": \"Zénith Arena Lille\",\n"
        + "                \"etatPrestation\": {\n"
        + "                    \"name\": \"PrestationRecue\",\n"
        + "                    \"label\": \"Prestation reçue\"\n"
        + "                },\n"
        + "                \"mandant\": \"covea-expert\",\n"
        + "                \"dateCreation\": \"2018-07-13T14:44:54+0200\"\n"
        + "            },\n"
        + "            \"links\": []\n"
        + "        }\n"
        + "    ],\n"
        + "    \"links\": [\n"
        + "        {\n"
        + "            \"rel\": \"firstPage\",\n"
        + "            \"href\": \"/core/api/common/missions?prestataireId=5b489dc6130000be0078176b&nbPage=1&nbElements=16&referer=firstPage\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"rel\": \"lastPage\",\n"
        + "            \"href\": \"/core/api/common/missions?prestataireId=5b489dc6130000be0078176b&nbPage=1&nbElements=16&referer=lastPage\"\n"
        + "        }\n"
        + "    ],\n"
        + "    \"filters\": {\n"
        + "        \"/assureurId\": {\n"
        + "            \"type\": {\n"
        + "                \"array\": {\n"
        + "                    \"type\": \"BSONObjectID\"\n"
        + "                }\n"
        + "            },\n"
        + "            \"optional\": true\n"
        + "        },\n"
        + "        \"/prestataireId\": {\n"
        + "            \"type\": {\n"
        + "                \"array\": {\n"
        + "                    \"type\": \"BSONObjectID\"\n"
        + "                }\n"
        + "            },\n"
        + "            \"optional\": true\n"
        + "        },\n"
        + "        \"/departement\": {\n"
        + "            \"type\": {\n"
        + "                \"array\": {\n"
        + "                    \"type\": \"string\"\n"
        + "                }\n"
        + "            },\n"
        + "            \"optional\": true\n"
        + "        },\n"
        + "        \"/cloture\": {\n"
        + "            \"type\": \"boolean\",\n"
        + "            \"optional\": true\n"
        + "        },\n"
        + "        \"/startDateQuery\": {\n"
        + "            \"type\": \"LocalDate\",\n"
        + "            \"optional\": true\n"
        + "        },\n"
        + "        \"/endDateQuery\": {\n"
        + "            \"type\": \"LocalDate\",\n"
        + "            \"optional\": true\n"
        + "        },\n"
        + "        \"/contentQuery\": {\n"
        + "            \"type\": \"string\",\n"
        + "            \"optional\": true\n"
        + "        },\n"
        + "        \"/typeMissionQuery\": {\n"
        + "            \"type\": {\n"
        + "                \"array\": {\n"
        + "                    \"oneOf\": [\n"
        + "                        {\n"
        + "                            \"name\": \"ExpertiseCovea\",\n"
        + "                            \"label\": \"Expertise\"\n"
        + "                        }\n"
        + "                    ]\n"
        + "                }\n"
        + "            },\n"
        + "            \"optional\": true\n"
        + "        },\n"
        + "        \"/etapeMission\": {\n"
        + "            \"type\": {\n"
        + "                \"array\": {\n"
        + "                    \"oneOf\": [\n"
        + "                        {\n"
        + "                            \"name\": \"PrestationRecue\",\n"
        + "                            \"label\": \"Prestation reçue\"\n"
        + "                        },\n"
        + "                        {\n"
        + "                            \"name\": \"PrestationQualifiee\",\n"
        + "                            \"label\": \"Prestation qualifiée\"\n"
        + "                        },\n"
        + "                        {\n"
        + "                            \"name\": \"RendezVousPris\",\n"
        + "                            \"label\": \"Rendez-vous pris\"\n"
        + "                        },\n"
        + "                        {\n"
        + "                            \"name\": \"CompteRenduDepose\",\n"
        + "                            \"label\": \"Compte rendu déposé\"\n"
        + "                        },\n"
        + "                        {\n"
        + "                            \"name\": \"ConclusionsDeposees\",\n"
        + "                            \"label\": \"Conclusions déposées\"\n"
        + "                        }\n"
        + "                    ]\n"
        + "                }\n"
        + "            },\n"
        + "            \"optional\": true\n"
        + "        }\n"
        + "    }\n"
        + "}";

    // When
    ListeAbstractMissions mapped = objectMapper
        .readValue(jsonDataTypes,
                   ListeAbstractMissions.class);

    // Then
    assertThat(mapped).isNotNull();
  }

  @Test
  public void mission_should_be_parsed() throws IOException {

    // Given
    String jsonDataTypes = "{\n"
        + "    \"href\": \"/core/api/covea-expert/missions/5b489f0910000044017610bd\",\n"
        + "    \"properties\": {\n"
        + "        \"dossier\": {\n"
        + "            \"assureurId\": \"5b489d591300006100781693\",\n"
        + "            \"contrat\": {\n"
        + "                \"numero\": \"123456789AA\",\n"
        + "                \"typeContrat\": \"MRH-VIP\",\n"
        + "                \"activitesSouscrites\": [\n"
        + "                    \"Concert\",\n"
        + "                    \"Spectacle\"\n"
        + "                ],\n"
        + "                \"informationsSpecifiques\": \"Grandes salles de spectacle\",\n"
        + "                \"franchise\": {\n"
        + "                    \"value\": {\n"
        + "                        \"montant\": 110\n"
        + "                    },\n"
        + "                    \"name\": \"Fixe\",\n"
        + "                    \"label\": \"Fixe\"\n"
        + "                },\n"
        + "                \"apporteur\": {\n"
        + "                    \"nom\": \"MMA Place Strasbourg Massena\",\n"
        + "                    \"adresse\": {\n"
        + "                        \"adresse1\": \" 3 Place de Strasbourg\",\n"
        + "                        \"codePostal\": \"59800\",\n"
        + "                        \"localite\": \"Lille\",\n"
        + "                        \"codePays\": \"FR\",\n"
        + "                        \"nomPays\": \"France\"\n"
        + "                    },\n"
        + "                    \"coordonnees\": {\n"
        + "                        \"telPersonnel\": \"string\",\n"
        + "                        \"telProfessionnel\": \"string\",\n"
        + "                        \"telPortable\": \"string\",\n"
        + "                        \"email\": \"annie.barreau@libertysurf.fr\",\n"
        + "                        \"fax\": \"string\"\n"
        + "                    }\n"
        + "                },\n"
        + "                \"professionnel\": true,\n"
        + "                \"dateSouscription\": \"2010-01-01\",\n"
        + "                \"dateModification\": \"2016-07-01\",\n"
        + "                \"dateValeur\": \"2010-01-01\",\n"
        + "                \"numeroAccord\": \"Temp457\",\n"
        + "                \"garanties\": [\n"
        + "                    {\n"
        + "                        \"id\": \"5b489f0910000044017610ba\",\n"
        + "                        \"typeGarantie\": {\n"
        + "                            \"name\": \"Incendie\",\n"
        + "                            \"label\": \"Incendie\"\n"
        + "                        },\n"
        + "                        \"typeGarantieComplementaire\": {\n"
        + "                            \"name\": \"AppareilsElectriques\",\n"
        + "                            \"label\": \"Appareils Electriques\"\n"
        + "                        },\n"
        + "                        \"plafonds\": [\n"
        + "                            {\n"
        + "                                \"objetPlafonne\": {\n"
        + "                                    \"name\": \"PlafondVeranda\",\n"
        + "                                    \"label\": \"Plafond véranda\"\n"
        + "                                },\n"
        + "                                \"valeur\": 5000,\n"
        + "                                \"description\": \"Pour les vérandas ALU\"\n"
        + "                            }\n"
        + "                        ],\n"
        + "                        \"franchise\": {\n"
        + "                            \"value\": {\n"
        + "                                \"montant\": 150\n"
        + "                            },\n"
        + "                            \"name\": \"Fixe\",\n"
        + "                            \"label\": \"Fixe\"\n"
        + "                        }\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": \"5b489f0910000044017610bb\",\n"
        + "                        \"typeGarantie\": {\n"
        + "                            \"name\": \"Incendie\",\n"
        + "                            \"label\": \"Incendie\"\n"
        + "                        },\n"
        + "                        \"plafonds\": []\n"
        + "                    }\n"
        + "                ],\n"
        + "                \"sinistralites\": []\n"
        + "            },\n"
        + "            \"risques\": [\n"
        + "                {\n"
        + "                    \"adresse\": {\n"
        + "                        \"adresse1\": \"1 Boulevard des Cités Unies\",\n"
        + "                        \"codePostal\": \"59777\",\n"
        + "                        \"localite\": \"Lille\",\n"
        + "                        \"codePays\": \"FR\",\n"
        + "                        \"nomPays\": \"France\"\n"
        + "                    },\n"
        + "                    \"typeRisque\": {\n"
        + "                        \"name\": \"MaisonParticuliere\",\n"
        + "                        \"label\": \"Maison particulière\"\n"
        + "                    },\n"
        + "                    \"usageAssure\": {\n"
        + "                        \"name\": \"ResidencePrincipale\",\n"
        + "                        \"label\": \"Résidence principale\"\n"
        + "                    },\n"
        + "                    \"description\": \"Maison de campagne avec dépendances\",\n"
        + "                    \"mesures\": [\n"
        + "                        {\n"
        + "                            \"typeMesure\": {\n"
        + "                                \"label\": \"Superficie\",\n"
        + "                                \"name\": \"Superficie\",\n"
        + "                                \"value\": {\n"
        + "                                    \"unite\": \"m²\",\n"
        + "                                    \"unites\": \"m²\"\n"
        + "                                }\n"
        + "                            },\n"
        + "                            \"valeur\": 280\n"
        + "                        }\n"
        + "                    ],\n"
        + "                    \"risqueConcerne\": true,\n"
        + "                    \"risqueMoins2ans\": false,\n"
        + "                    \"risquesAggraves\": [],\n"
        + "                    \"niveauProtection\": \"5\",\n"
        + "                    \"risqueAtypique\": true,\n"
        + "                    \"anneeConstruction\": 1888,\n"
        + "                    \"indicateurs\": [\n"
        + "                        {\n"
        + "                            \"typeIndicateur\": {\n"
        + "                                \"name\": \"Alarme\",\n"
        + "                                \"label\": \"Alarme\"\n"
        + "                            },\n"
        + "                            \"valeur\": true\n"
        + "                        }\n"
        + "                    ]\n"
        + "                }\n"
        + "            ],\n"
        + "            \"sinistre\": {\n"
        + "                \"reference\": \"REF-EAD-20180713-02\",\n"
        + "                \"caracteristiques\": {\n"
        + "                    \"nature\": {\n"
        + "                        \"name\": \"Incendie\",\n"
        + "                        \"label\": \"Incendie\"\n"
        + "                    },\n"
        + "                    \"cause\": {\n"
        + "                        \"name\": \"AppareilChauffage\",\n"
        + "                        \"label\": \"Appareil de chauffage\"\n"
        + "                    },\n"
        + "                    \"detail\": {\n"
        + "                        \"name\": \"Autre\",\n"
        + "                        \"label\": \"Autre\"\n"
        + "                    }\n"
        + "                },\n"
        + "                \"date\": \"2018-01-07\",\n"
        + "                \"heure\": \"17:00:00\",\n"
        + "                \"adresse\": {\n"
        + "                    \"adresse1\": \"1 Boulevard des Cités Unies\",\n"
        + "                    \"codePostal\": \"59777\",\n"
        + "                    \"localite\": \"Lille\",\n"
        + "                    \"codePays\": \"FR\",\n"
        + "                    \"nomPays\": \"France\"\n"
        + "                },\n"
        + "                \"dommagesConstates\": \"Plusieurs chaises brulées, une centaine\",\n"
        + "                \"circonstances\": \"Lors d'un concert, le piano prend feu\",\n"
        + "                \"piecesEndommagees\": [],\n"
        + "                \"vitresEndommagees\": [],\n"
        + "                \"rappelMesuresConservatoires\": \"Aucun car fondation seine\"\n"
        + "            },\n"
        + "            \"acteurs\": [\n"
        + "                {\n"
        + "                    \"informationsAssure\": {\n"
        + "                        \"profession\": \"Organisateur d'événements\",\n"
        + "                        \"situationComptable\": \"En cours\"\n"
        + "                    },\n"
        + "                    \"id\": \"5b489f0910000044017610bc\",\n"
        + "                    \"personne\": {\n"
        + "                        \"nom\": \"Zénith Arena Lille\",\n"
        + "                        \"adresse\": {\n"
        + "                            \"adresse1\": \"1 Boulevard des Cités Unies\",\n"
        + "                            \"codePostal\": \"59777\",\n"
        + "                            \"localite\": \"Lille\",\n"
        + "                            \"codePays\": \"FR\",\n"
        + "                            \"nomPays\": \"France\"\n"
        + "                        },\n"
        + "                        \"coordonnees\": {\n"
        + "                            \"email\": \"zenitharenalille@fakemail.fr\"\n"
        + "                        }\n"
        + "                    },\n"
        + "                    \"references\": [\n"
        + "                        {\n"
        + "                            \"typeReference\": {\n"
        + "                                \"name\": \"ReferenceSinistre\",\n"
        + "                                \"label\": \"Référence sinistre\"\n"
        + "                            },\n"
        + "                            \"valeur\": \"RefAssure\"\n"
        + "                        }\n"
        + "                    ],\n"
        + "                    \"archive\": false,\n"
        + "                    \"representants\": [],\n"
        + "                    \"typeActeur\": {\n"
        + "                        \"name\": \"Assure\",\n"
        + "                        \"label\": \"Assuré\"\n"
        + "                    },\n"
        + "                    \"relationAuRisque\": {\n"
        + "                        \"name\": \"ProprietaireNonOccupant\",\n"
        + "                        \"label\": \"Propriétaire non occupant\"\n"
        + "                    },\n"
        + "                    \"responsableSinistre\": false,\n"
        + "                    \"misEnCause\": true,\n"
        + "                    \"lese\": false,\n"
        + "                    \"acteurConvoque\": false,\n"
        + "                    \"acteurPresent\": false\n"
        + "                }\n"
        + "            ],\n"
        + "            \"franchiseApplicable\": {\n"
        + "                \"value\": {\n"
        + "                    \"montant\": 110\n"
        + "                },\n"
        + "                \"name\": \"Fixe\",\n"
        + "                \"label\": \"Fixe\"\n"
        + "            }\n"
        + "        },\n"
        + "        \"mission\": {\n"
        + "            \"prestataireId\": \"5b489dc6130000be0078176b\",\n"
        + "            \"assureurId\": \"5b489d591300006100781693\",\n"
        + "            \"dossierId\": \"5b489f0910000044017610b9\",\n"
        + "            \"dateDeMissionnement\": \"2018-07-03T10:00:00.556+02:00[Europe/Paris]\",\n"
        + "            \"numero\": \"0004\",\n"
        + "            \"commentaires\": [],\n"
        + "            \"statut\": {\n"
        + "                \"name\": \"Ouverte\",\n"
        + "                \"label\": \"Ouverte\"\n"
        + "            },\n"
        + "            \"etape\": {\n"
        + "                \"name\": \"PrestataireMissionne\",\n"
        + "                \"label\": \"Prestataire missionné\"\n"
        + "            },\n"
        + "            \"typeMission\": {\n"
        + "                \"name\": \"ExpertiseCovea\",\n"
        + "                \"label\": \"Expertise\"\n"
        + "            },\n"
        + "            \"prestationHasEvaluationDesDommages\": false,\n"
        + "            \"prestationHasChiffrage\": false\n"
        + "        },\n"
        + "        \"id\": \"5b489f0910000044017610bd\",\n"
        + "        \"version\": 1,\n"
        + "        \"dateDeCreation\": \"2018-07-13T14:46:01+0200\",\n"
        + "        \"dateDeDerniereModification\": \"2018-07-13T14:46:01+0200\"\n"
        + "    },\n"
        + "    \"links\": [\n"
        + "        {\n"
        + "            \"rel\": \"commands\",\n"
        + "            \"href\": \"/core/api/covea-expert/missions/5b489f0910000044017610bd/commands?referer=commands\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"rel\": \"events\",\n"
        + "            \"href\": \"/core/api/covea-expert/missions/5b489f0910000044017610bd/events?referer=events\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"rel\": \"linked-events\",\n"
        + "            \"href\": \"/core/api/covea-expert/missions/5b489f0910000044017610bd/linkedEvents?referer=linked-events\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"rel\": \"eventsNotCreatedByMe\",\n"
        + "            \"href\": \"/core/api/covea-expert/missions/5b489f0910000044017610bd/othersEvents?referer=eventsNotCreatedByMe\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"rel\": \"prestataire\",\n"
        + "            \"href\": \"/core/api/partenaire/partenaires/5b489dc6130000be0078176b/public?referer=prestataire\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"rel\": \"assureur\",\n"
        + "            \"href\": \"/core/api/partenaire/partenaires/5b489d591300006100781693/public?referer=assureur\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"rel\": \"piecesJointes\",\n"
        + "            \"href\": \"/core/api/pieceJointe/piecesJointes?missionId=5b489f0910000044017610bd&archived=false&referer=piecesJointes\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"rel\": \"synthese\",\n"
        + "            \"href\": \"/core/api/covea-expert/synthese?missionId=5b489f0910000044017610bd&referer=synthese\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"rel\": \"historique\",\n"
        + "            \"href\": \"/core/api/covea-expert/historique?missionId=5b489f0910000044017610bd&referer=historique\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"rel\": \"prestations\",\n"
        + "            \"href\": \"/core/api/covea-expert/prestation?missionId=5b489f0910000044017610bd&referer=prestations\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"rel\": \"difficultes\",\n"
        + "            \"href\": \"/core/api/covea-expert/difficulte?missionId=5b489f0910000044017610bd&referer=difficultes\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"rel\": \"chiffrages\",\n"
        + "            \"href\": \"/core/api/covea-expert/chiffrages?missionId=5b489f0910000044017610bd&archived=false&referer=chiffrages\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"rel\": \"recours\",\n"
        + "            \"href\": \"/core/api/covea-expert/recours?missionId=5b489f0910000044017610bd&archived=false&referer=recours\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"rel\": \"reglements\",\n"
        + "            \"href\": \"/core/api/covea-expert/reglements?missionId=5b489f0910000044017610bd&referer=reglements\"\n"
        + "        }\n"
        + "    ]\n"
        + "}";

    // When
    RessourceMission ressourceMission = objectMapper
        .readValue(jsonDataTypes,
                   RessourceMission.class);

    // Then
    assertThat(ressourceMission).isNotNull();
  }
}
